$lines = @(
"package cli",
"",
"import (",
`	`"fmt`",
`	`"regexp`",
`	`"strings`",
")",
"",
"type ViewType string",
"",
"const (",
`	`"ViewUser      ViewType = `"user`"`",
`	`"ViewSystem    ViewType = `"system`"`",
`	`"ViewInterface ViewType = `"interface`"`",
`	`"ViewACL       ViewType = `"acl`"`",
")",
"",
"type Command struct {",
`	`"Raw     string`",
`	`"Command string`",
`	`"Args    []string`",
")",
"",
"type CLIState struct {",
`	`"CurrentView  ViewType`",
`	`"CurrentSub   string`",
`	`"DeviceConfig map[string]string`",
`	`"ACLs         map[string][]*ACLRule`",
`	`"Routes       []*RouteEntry`",
")",
"",
"type ACLRule struct {",
`	`"ID          int`",
`	`"Action      string`",
`	`"Protocol    string`",
`	`"SrcIP       string`",
`	`"SrcWildcard string`",
`	`"DstIP       string`",
`	`"DstWildcard string`",
")",
"",
"type RouteEntry struct {",
`	`"Destination string`",
`	`"Mask        string`",
`	`"NextHop     string`",
`	`"Protocol    string`",
")",
"",
"func NewCLIState() *CLIState {",
`	`"return &CLIState{",
`		`"CurrentView:  ViewUser,`",
`		`"DeviceConfig: make(map[string]string),`",
`		`"ACLs:         make(map[string][]*ACLRule),`",
`		`"Routes:       []*RouteEntry{},`",
`	`"}",
"}",
"",
"func ParseCommand(input string) *Command {",
`	`"input = strings.TrimSpace(input)`",
`	`"if input == `\"`\" { return nil }`",
`	`"parts := strings.Fields(input)`",
`	`"if len(parts) == 0 { return nil }`",
`	`"return &Command{Raw: input, Command: parts[0], Args: parts[1:]}",
"}",
"",
"func ExecuteCommand(state *CLIState, cmd *Command) string {",
`	`"if cmd == nil { return `\"`\" }"`,
`	`"command := strings.ToLower(cmd.Command)"`,
`	`"switch command {"`,
`	`"case `\"system-view`\", `\"sys`\":\"`,
`		`"state.CurrentView = ViewSystem"`,
`		`"return `\"Enter system view`\""`,
`	`"case `\"quit`\", `\"q`\":\"`,
`		`"if state.CurrentView == ViewSystem {"`,
`			`"state.CurrentView = ViewUser"`,
`		`"} else {"`,
`			`"state.CurrentView = ViewSystem"`,
`		`"}"`,
`		`"state.CurrentSub = `\"`\""`,
`		`"return `\"Return`\""`,
`	`"case `\"interface`\", `\"int`\":\"`,
`		`"if state.CurrentView != ViewSystem || len(cmd.Args) == 0 {"`,
`			`"return `\"Error: invalid`\""`,
`		`"}"`,
`		`"ifName := cmd.Args[0]"`,
`		`"re := regexp.MustCompile(`^[gei]\d+/\d+/\d+$`)"`,
`		`"if !re.MatchString(ifName) {"`,
`			`"return fmt.Sprintf(`\"Error: invalid interface '`%s`'`\", ifName)"`,
`		`"}"`,
`		`"state.CurrentView = ViewInterface"`,
`		`"state.CurrentSub = ifName"`,
`		`"return `\"Enter interface view`\""`,
`	`"case `\"ip`\":\"`,
`		`"if len(cmd.Args) == 0 { return `\"Error: need args`\" }"`,
`		`"subCmd := strings.ToLower(cmd.Args[0])"`,
`		`"switch subCmd {"`,
`		`"case `\"address`\":\"`,
`			`"if state.CurrentView != ViewInterface || len(cmd.Args) < 3 {"`,
`				`"return `\"Error: invalid`\""`,
`			`"}"`,
`			`"key := fmt.Sprintf(`\"interface:`%s`:ip`\", state.CurrentSub)"`,
`			`"state.DeviceConfig[key] = fmt.Sprintf(`\"`%s`/`%s`\", cmd.Args[1], cmd.Args[2])"`,
`			`"return fmt.Sprintf(`\"Set IP`\"`)"`,
`		`"case `\"route-static`\":\"`,
`			`"if state.CurrentView != ViewSystem || len(cmd.Args) < 4 {"`,
`				`"return `\"Error: invalid`\""`,
`			`"}"`,
`			`"state.Routes = append(state.Routes, &RouteEntry{"`,
`				`"Destination: cmd.Args[1], Mask: cmd.Args[2], NextHop: cmd.Args[3],"`,
`			`"})"`,
`			`"return `\"Static route added`\""`,
`		`"}"`,
`	`"case `\"display`\", `\"dis`\":\"`,
`		`"if len(cmd.Args) == 0 { return `\"Error: need args`\" }"`,
`		`"switch strings.ToLower(cmd.Args[0]) {"`,
`		`"case `\"current-configuration`\":\"`,
`			`"var out strings.Builder"`,
`			`"out.WriteString(`\"Current config:`n`\")"`,
`			`"for k, v := range state.DeviceConfig {"`,
`				`"out.WriteString(fmt.Sprintf(`\"  `%s`: `%s`n`\", k, v))"`,
`			`"}"`,
`			`"return out.String()"`,
`		`"case `\"routing-table`\":\"`,
`			`"var out strings.Builder"`,
`			`"out.WriteString(`\"Destination  NextHop`n`\")"`,
`			`"for _, r := range state.Routes {"`,
`				`"out.WriteString(fmt.Sprintf(`\"`%s`  `%s`n`\", r.Destination, r.NextHop))"`,
`			`"}"`,
`			`"return out.String()"`,
`		`"}"`,
`	`"case `\"acl`\":\"`,
`		`"if state.CurrentView != ViewSystem || len(cmd.Args) == 0 {"`,
`			`"return `\"Error: invalid`\""`,
`		`"}"`,
`		`"aclNum := cmd.Args[0]"`,
`		`"if _, ok := state.ACLs[aclNum]; !ok {"`,
`			`"state.ACLs[aclNum] = []*ACLRule{}"`,
`		`"}"`,
`		`"state.CurrentView = ViewACL"`,
`		`"state.CurrentSub = aclNum"`,
`		`"return `\"Enter ACL view`\""`,
`	`"case `\"rule`\":\"`,
`		`"if state.CurrentView != ViewACL || len(cmd.Args) < 3 {"`,
`			`"return `\"Error: invalid`\""`,
`		`"}"`,
`		`"rule := &ACLRule{"`,
`			`"Action: cmd.Args[0], Protocol: cmd.Args[1],"`,
`		`"}"`,
`		`"state.ACLs[state.CurrentSub] = append(state.ACLs[state.CurrentSub], rule)"`,
`		`"return `\"Rule added`\""`,
`	`"case `\"sysname`\":\"`,
`		`"if state.CurrentView != ViewSystem || len(cmd.Args) == 0 {"`,
`			`"return `\"Error: invalid`\""`,
`		`"}"`,
`		`"state.DeviceConfig[`\"sysname`\"] = cmd.Args[0]"`,
`		`"return fmt.Sprintf(`\"Sysname set to '`%s`'`\", cmd.Args[0])"`,
`	`"case `\"ping`\":\"`,
`		`"if len(cmd.Args) == 0 { return `\"Error: need target`\" }"`,
`		`"return fmt.Sprintf(`\"Ping`%s`: success`\", cmd.Args[0])"`,
`	`"}"`,
`	`"return fmt.Sprintf(`\"Error: unknown command '`%s`'`\", cmd.Command)"`,
"}",
"",
"func GetPrompt(state *CLIState, deviceName string) string {",
`	`"if n, ok := state.DeviceConfig[`\"sysname`\"]; ok { deviceName = n }"`,
`	`"if deviceName == `\"`\" { deviceName = `\"Router`\" }"`,
`	`"switch state.CurrentView {"`,
`	`"case ViewUser:",
`		`"return fmt.Sprintf(`\"[`%s`]`\", deviceName)"`,
`	`"case ViewInterface:",
`		`"return fmt.Sprintf(`\"[`%s`-`%s`]`\", deviceName, state.CurrentSub)"`,
`	`"case ViewACL:",
`		`"return fmt.Sprintf(`\"[`%s`-acl-`%s`]`\", deviceName, state.CurrentSub)"`,
`	`"}"`,
`	`"return fmt.Sprintf(`\"[`%s`]`\", deviceName)"`,
"}"
)
[System.IO.File]::WriteAllLines("D:\Projects\Go\src\ensp-lab\internal\cli\parser.go", $lines)